
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Button

def submit_action():
    # Add your submit action here
    print("Submit button clicked")


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\TOR8HC\Documents\tkinfoloder\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("827x472")
window.configure(bg = "#6D6161")


canvas = Canvas(
    window,
    bg = "#6D6161",
    height = 472,
    width = 827,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    30.0,
    29.0,
    anchor="nw",
    text="LOGIN SYSTEM",
    fill="#FFFFFF",
    font=("Inter", 64 * -1)
)

canvas.create_text(
    34.0,
    197.0,
    anchor="nw",
    text="USER NAME:\n",
    fill="#FFFFFF",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    34.0,
    290.0,
    anchor="nw",
    text="PASSWORD:\n",
    fill="#FFFFFF",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    34.0,
    290.0,
    anchor="nw",
    text="PASSWORD:\n",
    fill="#FFFFFF",
    font=("Inter", 12 * -1)
)

canvas.create_rectangle(
    57.0,
    233.0,
    363.0,
    270.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    57.0,
    333.0,
    363.0,
    370.0,
    fill="#D9D9D9",
    outline="")

# Submit button
submit_button = Button(window, text="Submit", command=submit_action)
submit_button.place(x=57, y=400)  # Adjust coordinates as needed

window.resizable(False, False)
window.mainloop()